pub mod app;
pub mod settings;
pub mod programs;
pub mod displays;
pub mod infos;
pub mod keybinds;
pub mod appearance;
pub mod startup_programs;
pub mod overview;
pub mod wallpaper;
pub mod lockscreen;
mod input;

pub const OVERVIEW_PAGE: &str = "overview-page";
pub const GENERAL_PAGE: &str = "general-page";
pub const DISPLAY_PAGE: &str = "display-page";
pub const WALLPAPER_PAGE: &str = "wallpaper-page";
pub const LOCKSCREEN_PAGE: &str = "lockscreen-page";
pub const APPEARANCE_PAGE: &str = "appearance-page";
pub const STARTUP_PROGRAMS_PAGE: &str = "startup-page";
pub const INPUT_PAGE: &str = "input-page";
pub const KEYBINDS_PAGE: &str = "keybinds-page";
pub const INFO_PAGE: &str = "info-page";