use serde::{Deserialize, Serialize};
use crate::models::rgba_color::RGBAColor;

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct LockScreenSettings {
    pub hide_cursor: bool,
    pub grace: f32,
    pub fall_timeout: u32,
    pub lockscreen_wallpaper: String,
    pub blur_size: u32,
    pub blur_passes: u32,
    pub noise: f32,
    pub contrast: f32,
    pub brightness: f32,
    pub vibrancy: f32,
    pub input_width: u32,
    pub input_height: u32,
    pub input_outline_thickness: u32,
    pub input_dots_size: u32,
    pub input_dots_spacing: u32,
    pub input_dots_center: bool,
    pub input_outer_color: RGBAColor,
    pub input_inner_color: RGBAColor,
    pub input_font_color: RGBAColor,
    pub input_placeholder_text: String,
    pub hide_input: bool,
    pub input_x_position: u32,
    pub input_y_position: u32,
    pub input_vertical_alignment: String,
    pub input_horizontal_alignment: String,
    pub display_text: String,
    pub display_text_color: RGBAColor,
    pub display_text_font_size: u32,
    pub display_text_font: String,
    pub display_text_x_position: u32,
    pub display_text_y_position: u32,
    pub display_text_vertical_alignment: String,
    pub display_text_horizontal_alignment: String,
}