use serde::{Deserialize, Serialize};

#[derive(Eq, PartialEq, Hash, Debug, Clone, Serialize, Deserialize)]
pub enum SystemKeybind {
    Terminal,
    CloseWindow,
    ExitHyprland,
    FileManager,
    ToggleFloatingWindow,
    RunProgram,
    Pseudo,
    SplitWindow,
    Screenshot,
    ScreenshotWindow,
    LockScreen,
    EmojiSelector,
    FocusLeftWindow,
    FocusRightWindow,
    FocusTopWindow,
    FocusBottomWindow,
    SwitchWorkspaceOne,
    SwitchWorkspaceTwo,
    SwitchWorkspaceThree,
    SwitchWorkspaceFour,
    SwitchWorkspaceFive,
    SwitchWorkspaceSix,
    SwitchWorkspaceSeven,
    SwitchWorkspaceEight,
    SwitchWorkspaceNine,
    SwitchWorkspaceZero,
    MoveWorkspaceOne,
    MoveWorkspaceTwo,
    MoveWorkspaceThree,
    MoveWorkspaceFour,
    MoveWorkspaceFive,
    MoveWorkspaceSix,
    MoveWorkspaceSeven,
    MoveWorkspaceEight,
    MoveWorkspaceNine,
    MoveWorkspaceZero,
}