use gtk::gdk::RGBA;

#[derive(Debug)]
pub struct AppearanceSettings {
    pub wallpaper_path: String,
    pub force_default_wallpaper: bool,
    pub disable_hyprland_logo: bool,
    pub inner_gab: f64,
    pub outer_gab: f64,
    pub border_size: f64,
    pub active_border_color: RGBA,
    pub inactive_border_color: RGBA,
    pub resize_on_border: bool,
    pub allow_tearing: bool,
    pub rounding: f64,
    pub rounding_power: f64,
    pub dim_inactive: bool,
    pub active_opacity: f64,
    pub inactive_opacity: f64,
    pub active_shadow: bool,
    pub shadow_range: f64,
    pub shadow_render_power: f64,
    pub shadow_color: RGBA,
    pub active_blur: bool,
    pub blur_size: f64,
    pub blur_passes: usize,
    pub blur_vibrancy: f64,
    pub layout: String,
    pub master_status: String,
    pub pseudo_tiling: bool,
    pub split_preservation: bool,
}